version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: systemd
          command: systemctl restart docker
      - run:
          name: Print the Current Time
          command: date
